### ISSUE TITLE
Crash when a direbat take an item on server

### ISSUE THREAD

**Issue by celophys** [dvitski/direbats#24]
The crash log:
-- Head --
Thread: Server thread
Stacktrace:
	at net.teamhollow.direbats.entity.direbat.DirebatEntity.spawnItemParticles(DirebatEntity.java:286)
	at net.teamhollow.direbats.entity.direbat.DirebatEntity.method_5958(DirebatEntity.java:246)
	at net.minecraft.class_1308.method_6023(class_1308.java:744)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.teamhollow.direbats.entity.direbat.DirebatEntity.method_6007(DirebatEntity.java:215)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.teamhollow.direbats.entity.direbat.DirebatEntity.method_5773(DirebatEntity.java:185)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: direbats:direbat (net.teamhollow.direbats.entity.direbat.DirebatEntity)
	Entity ID: 388
	Entity Name: entity.direbats.direbat
	Entity's Exact location: -214.55, 64.00, -218.39
	Entity's Block location: World: (-215,64,-219), Chunk: (at 9,4,5 in -14,-14; contains blocks -224,0,-224 to -209,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

I am using 1.18.1

**Comment by dvitski** [comment]
Please update to the latest version of Direbats, this should be fixed :)
https://www.curseforge.com/minecraft/mc-mods/direbats/files/3605018
